import Head from "next/head";
import { useRouter } from "next/router";
import Parse from "parse/dist/parse.min.js";
import { ChangeEvent, FormEvent, useState } from "react";

import ThemeToggleBtn from "components/ThemeToggleBtn";
import Link from "next/link";

export default function Home() {
  const [searchField, setSearchField] = useState("");
  const router = useRouter();
  const handleSubmit = (v: FormEvent) => {
    v.preventDefault();
    router.push(`/${searchField}`);
  };

  return (
    <div>
      <Head>
        <title>پورتفولیو ساز</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="min-h-screen flex flex-col justify-center">
          {/* <ThemeToggleBtn {...{ darkMode, setDarkMode }} /> */}
          <div className="h-60 flex items-center justify-center flex-col space-y-10 mx-5">
            <h1 className="font-[yekanRe] text-4xl">پورتفولیو خودت بساز</h1>
            <Link href={"/auth/register"} passHref>
              <button className="border-2 border-black dark:border-white px-5 py-3 rounded-sm">
                ساخت پورتفولیو
              </button>
            </Link>
          </div>

          <form
            onSubmit={handleSubmit}
            className="flex flex-col items-center m-5"
          >
            <h2 className="text-xl m-5">جستجوی پورتفولیو</h2>
            <input
              className="bg-gray-300/70 border-2 border-gray-600 rounded-sm p-4 w-full md:w-1/3 lg:2/3"
              onChange={(v) => setSearchField(v.target.value)}
            />
            <button
              type="submit"
              className="border-2 border-black dark:border-white px-5 py-3 m-5 rounded-sm"
            >
              جستجو
            </button>
          </form>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
